# Generated by Django 3.2.15 on 2022-09-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('H', 'H')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='edad',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('V', 'V')], default=None, max_length=1),
        ),
    ]
