# Generated by Django 3.2.15 on 2022-09-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encontrador', models.CharField(max_length=20)),
                ('fecha_encontrado', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('lugar_encontrado', models.CharField(max_length=50)),
            ],
        ),
    ]
