# Generated by Django 3.2.15 on 2022-09-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='id_mascota',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
